autofix: true

# list of paths to ignore, uses gitignore syntaxes (executes before any rule)
ignore:
  - .git/

rules:
  # checks if file ends in a newline character
  end-of-file:
    # set to true to enable this rule
    enable: true
